basePath: /api/v1
definitions:
  gin.H:
    additionalProperties: {}
    type: object
  github_com_devpablocristo_tech-house_pkg_types.APIError:
    properties:
      code:
        type: integer
      context:
        additionalProperties: {}
        type: object
      details:
        type: string
      message:
        type: string
      type:
        $ref: '#/definitions/github_com_devpablocristo_tech-house_pkg_types.APIErrorType'
    type: object
  github_com_devpablocristo_tech-house_pkg_types.APIErrorType:
    enum:
    - NOT_FOUND
    - CONFLICT
    - BAD_REQUEST
    - INTERNAL_ERROR
    - VALIDATION_ERROR
    - UNAUTHORIZED
    - TIMEOUT
    - SERVICE_UNAVAILABLE
    - FORBIDDEN
    type: string
    x-enum-varnames:
    - APIErrNotFound
    - APIErrConflict
    - APIErrBadRequest
    - APIErrInternal
    - APIErrValidation
    - APIErrUnauthorized
    - APIErrTimeout
    - APIErrUnavailable
    - APIErrForbidden
  github_com_devpablocristo_tech-house_projects_customers-manager_internal_customer_adapters_inbound_transport.CustomerJson:
    properties:
      age:
        type: integer
      birth_date:
        type: string
      email:
        type: string
      id:
        type: integer
      last_name:
        type: string
      name:
        type: string
      phone:
        type: string
    required:
    - age
    - birth_date
    - email
    - last_name
    - name
    type: object
  github_com_devpablocristo_tech-house_projects_customers-manager_internal_customer_adapters_inbound_transport.GetCustomerResponse:
    properties:
      customer:
        $ref: '#/definitions/github_com_devpablocristo_tech-house_projects_customers-manager_internal_customer_adapters_inbound_transport.CustomerJson'
    type: object
  ? github_com_devpablocristo_tech-house_projects_customers-manager_internal_customer_adapters_inbound_transport.GetCustomersResponse
  : properties:
      customers:
        items:
          $ref: '#/definitions/github_com_devpablocristo_tech-house_projects_customers-manager_internal_customer_adapters_inbound_transport.CustomerJson'
        type: array
    type: object
  github_com_devpablocristo_tech-house_projects_customers-manager_internal_customer_adapters_inbound_transport.GetKPIJson:
    properties:
      age_std_deviation:
        type: number
      average_age:
        type: number
    type: object
host: localhost:8080
info:
  contact: {}
  description: API para gestión de clientes
  title: Customer Manager API
  version: "1.0"
paths:
  /customers:
    get:
      description: Obtiene la lista de todos los clientes
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_devpablocristo_tech-house_projects_customers-manager_internal_customer_adapters_inbound_transport.GetCustomersResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_devpablocristo_tech-house_pkg_types.APIError'
      summary: Get list of customers
      tags:
      - customers
    post:
      consumes:
      - application/json
      description: Crea un nuevo cliente
      parameters:
      - description: Customer Data
        in: body
        name: customer
        required: true
        schema:
          $ref: '#/definitions/github_com_devpablocristo_tech-house_projects_customers-manager_internal_customer_adapters_inbound_transport.CustomerJson'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_devpablocristo_tech-house_pkg_types.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_devpablocristo_tech-house_pkg_types.APIError'
      summary: Create customer
      tags:
      - customers
  /customers/{id}:
    delete:
      description: Elimina un cliente
      parameters:
      - description: Customer ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_devpablocristo_tech-house_pkg_types.APIError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_devpablocristo_tech-house_pkg_types.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_devpablocristo_tech-house_pkg_types.APIError'
      summary: Delete customer
      tags:
      - customers
    get:
      description: Obtiene un cliente por su ID
      parameters:
      - description: Customer ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_devpablocristo_tech-house_projects_customers-manager_internal_customer_adapters_inbound_transport.GetCustomerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_devpablocristo_tech-house_pkg_types.APIError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_devpablocristo_tech-house_pkg_types.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_devpablocristo_tech-house_pkg_types.APIError'
      summary: Get customer by ID
      tags:
      - customers
    put:
      consumes:
      - application/json
      description: Actualiza un cliente existente
      parameters:
      - description: Customer ID
        in: path
        name: id
        required: true
        type: integer
      - description: Customer Data
        in: body
        name: customer
        required: true
        schema:
          $ref: '#/definitions/github_com_devpablocristo_tech-house_projects_customers-manager_internal_customer_adapters_inbound_transport.CustomerJson'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_devpablocristo_tech-house_pkg_types.APIError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_devpablocristo_tech-house_pkg_types.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_devpablocristo_tech-house_pkg_types.APIError'
      summary: Update customer
      tags:
      - customers
  /customers/kpi:
    get:
      description: Obtiene los KPIs de clientes
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_devpablocristo_tech-house_projects_customers-manager_internal_customer_adapters_inbound_transport.GetKPIJson'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_devpablocristo_tech-house_pkg_types.APIError'
      summary: Get KPIs
      tags:
      - customers
  /health:
    get:
      description: Verifica el estado del servicio
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
      summary: Health check
      tags:
      - system
  /ping:
    get:
      description: Simple ping para verificar conectividad
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
      summary: Ping
      tags:
      - system
  /protected/ping:
    get:
      description: Ping protegido que requiere autenticación
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_devpablocristo_tech-house_pkg_types.APIError'
      security:
      - ApiKeyAuth: []
      summary: Protected ping
      tags:
      - system
swagger: "2.0"
